name: terraform validate
on:
  - pull_request
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: terraform init
      run: terraform init -input=false -backend=false

    - name: terraform validate
      run: terraform validate

    - name: terraform init
      run: terraform init -input=false -backend=false
      with:
        working-dir: module

    - name: terraform validate
      run: terraform validate
      with:
        working-dir: module